### ISSUE TITLE
Support configuring Personal Token

### ISSUE THREAD

**Issue by antfu** [antfu/github-doorcat#12]
- [ ] UI for config
- [ ] Use the token to fetch

**Comment by exbotanical** [comment]
For this feature, are we thinking something along the lines of:
  1. user pastes PAT via the UI
  2. app persists PAT in `localStorage` 

Oauth requires app-specific secrets, and this project doesn't have a backend that could manage sessions. I'm thinking any risk of using `localStorage` is tolerable to this project given PATs are revocable. Thoughts?

**Comment by antfu** [comment]
We use extension storage for options instead of github.com, it should be in a isolated context and shouldn't be accessible by other scripts

**Comment by lishoulong** [comment]
Hi, @antfu , I just spend a few times configuring the PAT, So from user friendly perspective,  i suggest add a link to the page for easily getting the PAT.
