### ISSUE TITLE
[feature-req] Ability to rename pinned repo

### ISSUE THREAD

**Issue by jd-solanki** [antfu/github-doorcat#8]
Hi,

I am a fan of what you create for developers. I just realized that I have to use amazing "doorcat" as well for my github.

## Problem
One thing I experienced is when I pinned the multiple relative repo I am unable to identify the actual repo I want to navigate because there is lots of repos with the same prefix.

## Alternatives
I am using bookmarks for now (renamed bookmarks).

Regards.

**Comment by antfu** [comment]
Can you share an example of what the mapping will be like? We have an internal flag to hide the owner name and later on will be an option when we made the options page.

**Comment by jd-solanki** [comment]
Sorry, I am unable to understand the mapping.

I didn't check the source code. I installed the extension in GitHub and tried pinning the repo I usually use and found about this scenario.

**Comment by antfu** [comment]
Like, can you share an example of why you want to rename repos, like from what to what. I am trying to understand the context here and maybe we could come up with a better solution.

**Comment by jd-solanki** [comment]
I have two repos with the following names:
1. materio-vuetify-vuejs-admin-template-free `(public)`
2. materio-vuetify-vuejs-admin-template `(private)`

When I pin both repos I will only get few letters. I can differentiate both repos using that `-free` postfix but as dropdown truncates name I need rename ability.

In the below screenshot, I have only single repo pinned but you understand what I was talking about.

![Screenshot from 2021-09-15 17-58-39](https://user-images.githubusercontent.com/47495003/133433380-181d5044-ab75-428b-8564-5bcdca43627b.png)

So with rename ability I can rename to:
1. Materio Free
2. Materio Pro

**Comment by lishoulong** [comment]
Hi, @antfu I  would like to support this feature, is it ok in your idea?

**Comment by lishoulong** [comment]
@antfu I just drafted this feature again, I think we should do two things:
- Add ui for input 
We should add a input component using for inputting repo name, but how should we layout the ui.

- Change the data structor
change the data structor for the repos.pinned and repos.recent, the easiest way is to change the pinned and recent array list to customed name, but now we depend on the pinned and recent item to generate `github.dev` url and `owner  name`.
So I think we should change the data structor like follow:

``` javascript
// current type
interface repos = {
  lastUpdated: number
  recent: string[]
  pinned: string[]
  isShow: boolean
}
```
``` javascript
// new type
interface repos = {
  lastUpdated: number
  recent: {
    original: string;
    custom: string;
  }[]
  pinned: {
    original: string;
    custom: string;
  }[]
  isShow: boolean
}
```

**Comment by antfu** [comment]
> UI

We could have a pencil button and use native `prompt()` for input

> Data Structure

Maybe we could have 

```ts
interface repos = {
  lastUpdated: number
  recent: string[]
  pinned: string[]
  details: Record<string, { alias?: string }>
  isShow: boolean
}
```

**Comment by lishoulong** [comment]
ok, I think this repos structure should make sense, I will implement this feature but i have no auth to push to a branch, could you open auth for me.

**Comment by antfu** [comment]
You could fork it and push your branch there. Thanks

**Comment by lishoulong** [comment]
ok, get !
